In [1]:
from tensorflow import keras
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [12]:
img = cv2.imread('experimental_image.tiff', flags=cv2.IMREAD_GRAYSCALE)
print(img)
hist_img = cv2.equalizeHist(img)
cv2.imwrite('equalizeHist.png', hist_img)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


True