In [1]:
import numpy as np
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras import utils

print(utils.to_categorical(np.array([0, 1, 0]), num_classes=2))

[[1. 0.]
 [0. 1.]
 [1. 0.]]


In [12]:
import pandas as pd
data = pd.DataFrame([[1, 2, 3],
                     [2, 3, 5],
                     [1, 3, 4]], columns=['a', 'b', 'c'])

print(data.groupby(by=['b']).get_group(2).values[:, 1:])

[[2 3]]


In [13]:
from tensorflow.keras.preprocessing import sequence

a = [[1, 1, 1],
     [1, 2]]
print(sequence.pad_sequences(a, value=-2, padding='post', maxlen=3))
b = [[[1, 2, 1], [1, 2, 1]],
     [[1, 1, 1]]]
print(sequence.pad_sequences(b, value=0, padding='post', maxlen=2))

[[ 1  1  1]
 [ 1  2 -2]]
[[[1 2 1]
  [1 2 1]]

 [[1 1 1]
  [0 0 0]]]


In [1]:
import time

while True:
    time.sleep(10)
    print(1)

1
1
1
1
1
1
1
1
1
1
1


KeyboardInterrupt: 