In [1]:
import cv2
import numpy as np
print(cv2.__version__)

4.4.0


In [3]:
img = cv2.imread('lie_wen.png', cv2.IMREAD_GRAYSCALE)
print(img)
gyh_img = (img - np.min(img)) / (np.max(img) - np.min(img)) * 255
gyh_img = gyh_img.astype(np.uint8)
print(gyh_img)
cv2.imshow('gyh', gyh_img)
cv2.waitKey(0)

[[26 33 28 ... 94 96 93]
 [25 32 29 ... 92 94 91]
 [26 28 28 ... 94 93 91]
 ...
 [43 40 42 ... 90 91 94]
 [41 36 44 ... 91 91 89]
 [40 40 43 ... 91 90 85]]
[[ 33  42  36 ... 122 124 120]
 [ 32  41  37 ... 119 122 118]
 [ 33  36  36 ... 122 120 118]
 ...
 [ 55  52  54 ... 117 118 122]
 [ 53  46  57 ... 118 118 115]
 [ 52  52  55 ... 118 117 110]]


-1

In [2]:
img = cv2.imread('exp_x.png', cv2.IMREAD_GRAYSCALE)
print(img)
img = cv2.equalizeHist(img)
cv2.namedWindow('equal',cv2.WINDOW_NORMAL)
cv2.imshow('equal', img)
cv2.waitKey(0)

[[229 205 196 ... 236 236 236]
 [231 206 191 ... 236 236 237]
 [231 204 178 ... 235 236 236]
 ...
 [184 192 189 ... 220 220 220]
 [186 191 188 ... 220 221 219]
 [184 190 188 ... 220 220 220]]


-1

In [2]:
img = cv2.imread('experimental_image.tiff', cv2.IMREAD_GRAYSCALE)
clahe = cv2.createCLAHE(clipLimit=4, tileGridSize=(5, 5))
img = clahe.apply(img)
cv2.namedWindow('clahe', cv2.WINDOW_NORMAL)
cv2.imshow('clahe', img)
cv2.waitKey(0)
img = cv2.fastNlMeansDenoising(img, h=4, templateWindowSize=7, searchWindowSize=21)
cv2.imwrite('experi_1_ycl.png', img)
cv2.namedWindow('experi_1',cv2.WINDOW_NORMAL)
cv2.imshow('experi_1', img)
cv2.waitKey(0)


-1

In [10]:
img = cv2.imread('experi_2.tiff', cv2.IMREAD_GRAYSCALE)
clahe = cv2.createCLAHE(clipLimit=5.5, tileGridSize=(5, 5))
img = clahe.apply(img)
cv2.namedWindow('clahe_1', cv2.WINDOW_NORMAL)
cv2.imshow('clahe_1', img)
cv2.waitKey(0)
img = cv2.fastNlMeansDenoising(img, h=4, searchWindowSize=21, templateWindowSize=7)
cv2.imwrite('experi_2_ycl.png', img)
cv2.namedWindow('experi_2', cv2.WINDOW_NORMAL)
cv2.imshow('experi_2', img)
cv2.waitKey(0)


-1

In [7]:
img = cv2.GaussianBlur(img, (3, 3), 0)
canny_img = cv2.Canny(img, 100, 110)
cv2.imshow('canny', canny_img)
cv2.waitKey(0)

-1

In [4]:
import cv2
import numpy as np

img = cv2.imread('liewen_3_f.png', cv2.IMREAD_GRAYSCALE)

clahe = cv2.createCLAHE(clipLimit=4, tileGridSize=(5, 5))
img = clahe.apply(img)
# data = cv2.calcHist([img], [0], None, [256], [0, 255])
# print(data)
cv2.namedWindow('liewen', cv2.WINDOW_NORMAL)
cv2.imshow('liewen', img)
cv2.waitKey(0)
img = cv2.fastNlMeansDenoising(img, h=10, searchWindowSize=23, templateWindowSize=9)
cv2.namedWindow('liewen', cv2.WINDOW_NORMAL)
cv2.imshow('liewen', img)
cv2.waitKey(0)
img = cv2.GaussianBlur(img, (3, 3), 0)
cv2.namedWindow('liewen', cv2.WINDOW_NORMAL)
cv2.imshow('liewen', img)
cv2.waitKey(0)

canny_img = cv2.Canny(img, 60, 120)
cv2.namedWindow('liewen', cv2.WINDOW_NORMAL)
cv2.imwrite('canny_jieguo.png', canny_img)
cv2.imshow('liewen', canny_img)
cv2.waitKey(0)

-1