In [13]:
"""
n_estimator一般最大不超过300，除非数据量巨大
num_round是xgb本身的带的，是写在params参数之外的"""
import xgboost as xgb
from keras.datasets import boston_housing
import sklearn

(train_x, train_y), (test_x, test_y) = boston_housing.load_data()
print(train_x.shape)
print(train_y.shape)

(404, 13)
(404,)


In [25]:
model = xgb.XGBRegressor(n_estimators=100, max_depth=6, objective='reg:squarederror')
model.fit(train_x, train_y)

# 查看均方误差
print(sklearn.metrics.mean_squared_error(test_y, model.predict(test_x)))

# 默认返回R2系数（相关系数
print(model.score(train_x, train_y))

# 查看特征重要性
print(model.feature_importances_)


13.350520965428787
0.9976707707429318
[0.02216232 0.00201101 0.00733447 0.00223212 0.04379056 0.20303956
 0.0074023  0.0569986  0.00722806 0.02128241 0.01811873 0.00956893
 0.5988309 ]


In [22]:
import numpy as np
# 进行交叉验证, scoring参数默认模型自身的score，也可以自己给
sklearn.model_selection.cross_val_score(xgb.XGBRegressor(n_estimators=100, objective='reg:squarederror'),
                                        train_x, train_y,
                                        cv=4,
                                        scoring='neg_mean_squared_error')




array([ -8.572029  ,  -9.21625396, -12.6113526 , -13.05041845])

In [26]:
# 绘制学习曲线,该函数仅仅返回数据，真绘图还得自己用matplotlib写
cv = sklearn.model_selection.KFold(n_splits=4, shuffle=True, random_state=42)
train_size, train_score, test_score = sklearn.model_selection.learning_curve(model, # 这应该给一个没训练的模型
                                                                             train_x, train_y,
                                                                             shuffle=True,
                                                                             cv=cv)
print(train_size, train_score, test_score)
'学习曲线函数，告诉我们不同大小的训练集是否对模型有不同的帮助，即可以看我们从更多的数据中获益多少'
"""
衡量模型的好坏，一般是方差和偏差，bias和variance。而方法就是交叉验证
对于某个模型架构，使用交叉验证，看得分的平均值来衡量bias，看得分的方差来衡量模型variance
最后再弄一个综合指标来评估，比如：bias^2+variance+epsilon，
交叉验证意味着不同的训练和验证数据来衡量，如果variance小，则意味着模型稳定"""



[ 30  98 166 234 303] [[0.99999291 0.99994603 0.99998415 0.999985  ]
 [0.99989049 0.99990369 0.99997888 0.99981686]
 [0.99973009 0.99942851 0.99979654 0.99963913]
 [0.99927994 0.99928533 0.99940519 0.99898574]
 [0.99898739 0.99883677 0.99873724 0.99902223]] [[0.15080186 0.18814622 0.61536366 0.46169881]
 [0.79228696 0.77544282 0.70072185 0.68567951]
 [0.81988025 0.84573453 0.69508928 0.82189764]
 [0.85909034 0.87728246 0.70786183 0.85182035]
 [0.84762606 0.91175029 0.82734006 0.86191966]]
