In [2]:
from tensorflow import keras
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [6]:
img = cv2.imread('experimental_image.tiff', 0)
print(img)
# cv2.namedWindow('equal',cv2.WINDOW_NORMAL)
# cv2.imshow('equal', img)
# cv2.waitKey(0)

# img_1 = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
# print(img_1[:, :, 0])
# print(img_1[:, :, 0].shape)
# print(img_1[:, :, 1])
# print(img_1[:, :, 1].shape)
# print(img_1[:, :, 2])
# print(img_1[:, :, 2].shape)


[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
