In [1]:
import torch

In [2]:
# 创建张量并追踪计算历史
x = torch.ones(2, 2, dtype=torch.float,
               requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
# 做一次运算
y = x + 2
print(y)

print(y.grad_fn)

# 更多操作
print(y * y)
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [4]:
# requires_grad_ 原地改变了张量的此参数，如果未指定，是默认Flase
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (torch.square(a)).sum()
print(b.grad_fn)  # fn记录了这个tensor是如何被创建的，他的计算历史

False
True


In [5]:
# 梯度

In [6]:
# 开始反向传播，因为out是标量，于是
out.backward()

print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
# 反向传播必须是对标量，多输出神经网络输出的并不是向量！！！

# 雅可比向量积的这一特性使得将外部梯度输入到具有非标量输出的模型中变得非常方便
# 雅克比向量积的例子
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-1225.0953, -1048.4337,  -789.0477], grad_fn=<MulBackward0>)


In [16]:
# 此时y不再是标量，不能直接计算完整的雅可比矩阵，但若果想要雅克比向量积，只需将这个向量作为参数传给backward
# 也就是这里的v是向量y关于一个标量的函数的导数
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

# y.backward(torch.ones_like(y)) 这是对多输出模型的求导方法，也就是一般理解的反向传播


print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [9]:
# 也可以将代码块包装在no_grad中，来阻止autograd跟踪设置了requeires——grad的张量
print(x.requires_grad)
print(torch.square(x).requires_grad)

with torch.no_grad():
    print(torch.square(x).requires_grad)
    

True
True
False
