In [1]:
from __future__ import print_function
import torch


In [2]:
# 创建一个没有初始化的矩阵
x = torch.empty(5, 3)
print(x)

tensor([[4.5000e-39, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]])


In [3]:
# 随机初始化矩阵
x = torch.rand(5, 3)
print(x)

tensor([[0.7447, 0.7026, 0.2485],
        [0.0803, 0.8701, 0.6774],
        [0.2839, 0.2333, 0.5424],
        [0.4154, 0.9193, 0.9773],
        [0.2222, 0.6770, 0.2769]])


In [4]:
# 创造一个填满0且数据类型为long的矩阵
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 直接根据数据构造
x = torch.tensor([[1, 2]], dtype=torch.double)
print(x)
print(x.shape)
print(x.dtype)

tensor([[1., 2.]], dtype=torch.float64)
torch.Size([1, 2])
torch.float64


In [6]:
# 根据已有的tensor建立新tensor，默认继承原来，除非提供新值
x = torch.empty(4, 3, dtype=torch.int)
print(x)

# 有好几种new_
x = x.new_ones(3, 2, dtype=torch.double)
print(x)
print(x.dtype)
x = x.new_zeros(5, 3, dtype=torch.int)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
torch.float64
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[-0.6445,  0.5692,  0.0889],
        [ 1.1806,  0.9119,  0.2063],
        [ 1.8892, -0.9087, -1.6134],
        [-0.9783, -0.1762, -0.8344],
        [-0.6120, -2.0278, -0.3686]])


In [7]:
# 获取形状，本质上返回的是tuple，支持一切tuple的操作
print(x.size())

torch.Size([5, 3])


In [8]:
# 运算

In [9]:
# 加法
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

# 将结果输出到某个张量
result = torch.empty(x.shape)
torch.add(x, y, out=result)
print(result)

# 原地操作的加法
y.add_(x)  # 任何一个原地（in-place）操作后面都跟有下划线
print(y)

tensor([[-0.2744,  0.9939,  0.5435],
        [ 1.6934,  1.3109,  0.2401],
        [ 1.9445, -0.6642, -1.3281],
        [-0.0161,  0.6907, -0.5911],
        [-0.5561, -1.8614,  0.1059]])
tensor([[-0.2744,  0.9939,  0.5435],
        [ 1.6934,  1.3109,  0.2401],
        [ 1.9445, -0.6642, -1.3281],
        [-0.0161,  0.6907, -0.5911],
        [-0.5561, -1.8614,  0.1059]])
tensor([[-0.2744,  0.9939,  0.5435],
        [ 1.6934,  1.3109,  0.2401],
        [ 1.9445, -0.6642, -1.3281],
        [-0.0161,  0.6907, -0.5911],
        [-0.5561, -1.8614,  0.1059]])
tensor([[-0.2744,  0.9939,  0.5435],
        [ 1.6934,  1.3109,  0.2401],
        [ 1.9445, -0.6642, -1.3281],
        [-0.0161,  0.6907, -0.5911],
        [-0.5561, -1.8614,  0.1059]])


In [10]:
# 索引操作和标准numpy一样
print(x[1:, 0])

tensor([ 1.1806,  1.8892, -0.9783, -0.6120])


In [11]:
# 改变形状，可以用view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), z.size())

torch.Size([4, 4]) torch.Size([2, 8])


In [12]:
# 只有一个元素 可以用item得到数值
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7770])
0.7770328521728516


In [13]:
# 将torch的tensor转化为numpy(不支持charTensor的转化）
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [14]:
# numpy改变数值
a.add_(34)
print(a)
print(b)
# b实际是和a共享一个数据的

tensor([35., 35., 35., 35., 35.])
[35. 35. 35. 35. 35.]


In [15]:
# 将numpy转化为tensor
import numpy as np

a = np.ones(shape=(5, ))
b = torch.from_numpy(a)
# a = a + 10  # 如果这样加，会导致不再共享数据
np.add(a, 10, out=a)  # 这将会输出到原来的地址，保持共享

print(a)
print(b)

[11. 11. 11. 11. 11.]
tensor([11., 11., 11., 11., 11.], dtype=torch.float64)


In [16]:
# 使用.to将任何张量移动到GPU上
if torch.cuda.is_available():
    device = torch.device('cuda')  # CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建张量
    x = x.to(device=device)  # 或者后期移动上去
    z = x + y  # 此时z自动会存在GPU上
    print(z)
    print(z.to(device='cpu', dtype=torch.double))  # 移动回cpu，移动时可以改变类型


tensor([1.7770], device='cuda:0')
tensor([1.7770], dtype=torch.float64)
